version: '3'

services:
  mongo:
    image: mongo:3.7.9
    command: --smallfiles
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=athena

  athena:
    image: netshoes/athena-dependency-analyzer
    ports:
      - "8080:8080"
    links:
      - "rabbitmq"
      - "mongo"
    depends_on:
      - "rabbitmq"
      - "mongo"
    environment:
      - MONGO_URI=mongodb://mongo:27017/athena
      - RABBITMQ_ADDRESSES=rabbitmq:5672
      - RABBITMQ_HOST=athena
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - GITHUB_HOST=$GITHUB_HOST
      - GITHUB_ORGANIZATION=$GITHUB_ORGANIZATION
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - ADMIN_USERNAME=$ADMIN_USERNAME
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
